
export const EXPENSE_TYPES = [
  'Parking',
  'Travelling',
  'Hotel',
  'Telephone',
  'Travel',
  'Accommodation',
  'Meal',
  'PerDiem',
  'Phone',
  'Internet/Wifi',
  'Visa',
  'Gift',
  'Medical',
  'Other',
  'Courier',
  'Stationary',
  'Night Shift Allowance',
  'Taxi',
  'Food During Travel',
  'Client Dinner/Lunch',
  'Air Fare',
  'Cell Phone',
  'Visa Fee',
  'Car Rental',
  'Gas',
  'Recruitment Incentives',
].map((label) => ({ id: label, label }));
 