--------------------------------------------------------------------------------
-- 70_email_multibill.sql
--
-- Run as the APPLICATION SCHEMA, in SQL SCRIPTS. Idempotent. Safe on both
-- environments -- see the note on prod at the bottom.
--
--   dev  = karyasiddhitest.trinamix.com, schema HRMS
--   prod = karyasiddhi.trinamix.com,     schema REPO
--
--
-- THE GAP THIS CLOSES
-- -------------------
-- The multi-bill work (63-68) moved bill details out of EXPENSES and into
-- EXPENSE_ITEMS. Six endpoints, four handlers, two list queries and five app
-- files were updated to match.
--
-- SEND_EXPENSE_MAIL was not. It still read e.type and e.bill_no.
--
-- On dev, where script 64 dropped those columns, that surfaced honestly:
--
--   SEND_EXPENSE_MAIL      145  PL/SQL: SQL Statement ignored
--   SEND_EXPENSE_MAIL      147  ORA-00904: "E"."BILL_NO": invalid identifier
--   PROCESS_EXPENSE_ACTION  54  PLS-00905: object SEND_EXPENSE_MAIL is invalid
--
-- ...and because ORDS will not run a resource whose PL/SQL is invalid, every
-- protected endpoint answered a bare 403 with no body. Two hours went into
-- roles and privilege patterns, both of which were correct throughout. The
-- fault dictionary entry in DEPLOYMENT.md 12 says exactly this and it should
-- have been the first thing checked.
--
-- ON PROD IT IS WORSE, because it is silent. Section 3 of script 64 never
-- executed there -- SQL Commands skipped it -- so BILL_NO and TYPE still exist
-- on EXPENSES, the procedure still compiles, and every approval email has been
-- going out with an empty bill number and no bill list at all. A reviewer is
-- being asked to approve a total with nothing behind it.
--
--
-- WHAT CHANGES
-- ------------
-- 1. Claim-level fields come from CLAIM_FOR, not TYPE/BILL_NO.
--
-- 2. The claim table shows ONE money figure: the USD total. EXPENSES.AMOUNT is
--    now SUM(items.amount) across bills that may be in different currencies,
--    so printing it beside a single currency code would be a fabrication --
--    4500 INR when one of the bills was in EUR. Per-bill amounts appear in
--    their own currency, in the bill table.
--
-- 3. A bill table is added to both the plain-text and the HTML body: item no,
--    type, description, bill no, bill date, period, amount, USD, receipt --
--    with a total row, and a line explaining the USD-only total when the bills
--    are in more than one currency.
--
-- Everything else is byte-for-byte from 62_email_autonomous_read_fix.sql: the
-- TO/CC matrix, the actor-role parameter, the passed-in uncommitted values, the
-- no-manager and manager-has-no-email notes, the mail log. Those were hard won
-- and are not being retyped from memory -- this file was generated by patching
-- 62, not by rewriting it.
--
--
-- ORDER MATTERS. send_expense_mail must compile before process_expense_action,
-- which calls it in four places. Reversing them gives PLS-00306 / PLS-00905.
-- That has bitten this project twice.
--------------------------------------------------------------------------------

SET SERVEROUTPUT ON SIZE UNLIMITED
SET DEFINE OFF


--------------------------------------------------------------------------------
-- 0. Right schema, and the prerequisites the new body needs.
--------------------------------------------------------------------------------
DECLARE
  l_schema VARCHAR2(128) := SYS_CONTEXT('USERENV','CURRENT_SCHEMA');
  l_n      NUMBER;
BEGIN
  DBMS_OUTPUT.PUT_LINE('Connected as: ' || l_schema);
  DBMS_OUTPUT.PUT_LINE('  HRMS = dev (karyasiddhitest), REPO = PRODUCTION (karyasiddhi).');

  SELECT COUNT(*) INTO l_n FROM user_tables WHERE table_name = 'EXPENSE_ITEMS';
  IF l_n = 0 THEN
    RAISE_APPLICATION_ERROR(-20001,
      'No EXPENSE_ITEMS table on ' || l_schema || '. Run 64_multibill_stage1_clean.sql '
      || 'here first -- this email body reads it. Nothing changed.');
  END IF;

  SELECT COUNT(*) INTO l_n FROM user_tab_columns
  WHERE  table_name = 'EXPENSES' AND column_name = 'CLAIM_FOR';
  IF l_n = 0 THEN
    RAISE_APPLICATION_ERROR(-20001,
      'EXPENSES.CLAIM_FOR does not exist on ' || l_schema || '. Script 64 has not '
      || 'run here. Nothing changed.');
  END IF;

  SELECT COUNT(*) INTO l_n FROM user_tables WHERE table_name = 'EXPENSE_MAIL_LOG';
  IF l_n = 0 THEN
    RAISE_APPLICATION_ERROR(-20001,
      'No EXPENSE_MAIL_LOG on ' || l_schema || '. Run EMAIL_DEPLOY.sql here first. '
      || 'Nothing changed.');
  END IF;

  SELECT COUNT(*) INTO l_n FROM user_objects
  WHERE  object_name = 'PROCESS_EXPENSE_ACTION' AND object_type = 'PROCEDURE';
  IF l_n = 0 THEN
    RAISE_APPLICATION_ERROR(-20001,
      'PROCESS_EXPENSE_ACTION not found on ' || l_schema || '. Run EMAIL_DEPLOY.sql '
      || 'then 62 here first. Nothing changed.');
  END IF;

  DBMS_OUTPUT.PUT_LINE('Prerequisites OK.');
END;
/


--------------------------------------------------------------------------------
-- 1. send_expense_mail -- multi-bill aware. FIRST, because 2 depends on it.
--------------------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE send_expense_mail(
  p_expense_id  IN NUMBER,
  p_event       IN VARCHAR2,
  p_actor_empid IN NUMBER   DEFAULT NULL,
  p_comment     IN VARCHAR2 DEFAULT NULL,
  -- 'PROJECT_MANAGER' | 'FINANCE_MANAGER' | NULL.
  --
  -- Passed in because it CANNOT be derived here. is_finance_manager() answers
  -- "is this person the finance manager", not "which role were they acting in
  -- just now" -- and when one person is both the project manager and the
  -- finance manager, those differ. A manager revising at the MANAGER stage was
  -- labelled FM, and his remark filed under Fin.Manager Remarks.
  --
  -- Nor can current_stage be read back: process_expense_action has already
  -- moved it by the time this runs (to FINANCE on manager-accept, to NULL on
  -- final approval). The caller knows; it computed get_reviewer_role before
  -- touching anything.
  p_actor_role  IN VARCHAR2 DEFAULT NULL,
  -- Values the CALLER has just written but NOT yet committed.
  --
  -- This procedure is AUTONOMOUS, so it runs in its own transaction and cannot
  -- see the caller's uncommitted work. On submit that is fatal: the handler
  -- sets manager_empid and submitted_at, then calls this -- which re-reads the
  -- row and still sees an unsubmitted draft with no manager. The result was an
  -- email to the employee saying "no project manager is assigned", about a
  -- claim that had one.
  --
  -- Autonomy is still wanted: the mail log must survive a rolled-back
  -- approval, and APEX_MAIL.PUSH_QUEUE commits, which must not commit the
  -- caller's half-finished transaction. So instead of reading these three,
  -- the caller passes them. NULL means "not known, read from the row", which
  -- is correct for a manual call after the fact.
  p_manager_empid IN NUMBER    DEFAULT NULL,
  p_finance_empid IN NUMBER    DEFAULT NULL,
  p_submitted_at  IN TIMESTAMP DEFAULT NULL
) IS
  PRAGMA AUTONOMOUS_TRANSACTION;

  -- expense
  l_emp_id       NUMBER;
  l_mgr_id       NUMBER;
  l_fin_id       NUMBER;
  l_project_id   NUMBER;
  l_project_name VARCHAR2(400);
  l_amount       NUMBER;
  l_currency     VARCHAR2(3);
  l_amount_usd   NUMBER;
  l_exchange_rate NUMBER;
  -- Was l_type / l_bill_no, read from EXPENSES. Those columns are gone: a
  -- claim no longer HAS one type or one bill number, its bills do. See
  -- MULTI_BILL_PLAN.md.
  l_claim_for    VARCHAR2(400);
  l_item_count   NUMBER := 0;
  l_ccy_count    NUMBER := 0;
  l_submitted_at TIMESTAMP;

  -- people, as "Name(Ecode)"
  l_emp_label    VARCHAR2(400);
  l_mgr_label    VARCHAR2(400);
  l_fin_label    VARCHAR2(400);
  l_emp_name     VARCHAR2(300);
  l_mgr_name     VARCHAR2(300);
  l_fin_name     VARCHAR2(300);
  l_emp_email    VARCHAR2(255);
  l_mgr_email    VARCHAR2(255);
  l_fin_email    VARCHAR2(255);

  -- actor
  l_no_manager   BOOLEAN := FALSE;
  l_mgr_no_email BOOLEAN := FALSE;
  l_actor_name   VARCHAR2(300);
  l_actor_role   VARCHAR2(4);      -- 'PM' | 'FM'
  l_actor_label  VARCHAR2(400);

  -- remarks
  l_mgr_remarks  VARCHAR2(4000);
  l_fin_remarks  VARCHAR2(4000);

  l_to           VARCHAR2(4000);
  l_cc           VARCHAR2(4000);
  l_subject      VARCHAR2(400);
  l_greeting     VARCHAR2(400);
  l_body         CLOB;
  l_html         CLOB;
  l_rows         CLOB;
  l_bill_text    CLOB;   -- the bill list, plain
  l_bill_html    CLOB;   -- the bill list, HTML
  l_from         VARCHAR2(255);
  l_workspace    VARCHAR2(200);

  FUNCTION secret(p_name IN VARCHAR2) RETURN VARCHAR2 IS
    l_v VARCHAR2(200);
  BEGIN
    SELECT secret_value INTO l_v FROM app_secrets WHERE secret_name = p_name;
    RETURN l_v;
  EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL;
  END;

  -- One row of the claim table, in both formats at once, so the two bodies can
  -- never drift apart.
  PROCEDURE add_row(p_label IN VARCHAR2, p_value IN VARCHAR2) IS
  BEGIN
    l_body := l_body || RPAD(p_label, 22) || NVL(NULLIF(TRIM(p_value), ''), '-') || CHR(10);
    l_rows := l_rows
      || '<tr><td style="padding:4px 10px;border:1px solid #ddd;background:#f8fafc;'
      || 'white-space:nowrap"><b>' || p_label || '</b></td>'
      || '<td style="padding:4px 10px;border:1px solid #ddd">'
      || NVL(DBMS_XMLGEN.CONVERT(NULLIF(TRIM(p_value), '')), '-') || '</td></tr>';
  END;

  -- The claim total, in USD, as stamped on the row by recalc_claim_totals --
  -- not a fresh conversion. Restating an approved claim at today's rate would
  -- make the email disagree with the record.
  --
  -- USD ONLY, deliberately. EXPENSES.AMOUNT is now SUM(items.amount) across
  -- bills that may be in different currencies, so 4500 with a currency label
  -- of INR would be a fabrication when one bill was in EUR. The USD column is
  -- the only claim-level figure that means anything. Per-bill amounts appear
  -- in their own currency in the bill table below.
  FUNCTION total_usd_row RETURN VARCHAR2 IS
  BEGIN
    IF l_amount_usd IS NULL THEN
      RETURN NULL;   -- renders as '-'
    END IF;
    RETURN TO_CHAR(l_amount_usd) || ' USD'
           || CASE WHEN l_item_count > 0
                   THEN '   (' || l_item_count || ' bill'
                        || CASE WHEN l_item_count = 1 THEN '' ELSE 's' END || ')'
              END;
  END;

  -- The bill list. This is the substance of the email now -- the reviewer is
  -- being asked to approve a set of bills, and without this they see only a
  -- total and have to open the app to find out what it is made of.
  --
  -- Reads EXPENSE_ITEMS. Safe from an autonomous transaction because bills are
  -- saved and committed one request at a time, long before submit runs. The
  -- header columns are the ones that are uncommitted at that moment, which is
  -- why those arrive as parameters instead.
  PROCEDURE bill_table IS
  BEGIN
    IF l_item_count = 0 THEN
      l_bill_text := CHR(10) || 'This claim has no bills on it.' || CHR(10);
      l_bill_html := '<p style="padding:8px 10px;border:1px solid #f59e0b;'
        || 'background:#fef3c7;color:#92400e">This claim has no bills on it.</p>';
      RETURN;
    END IF;

    l_bill_text := CHR(10) || 'Bills (' || l_item_count || ')' || CHR(10)
                || RPAD('-', 60, '-') || CHR(10);
    l_bill_html := '<p style="font-weight:700;margin:14px 0 6px">Bills ('
                || l_item_count || ')</p>'
                || '<table style="border-collapse:collapse;border:1px solid #ddd;'
                || 'font-size:13px">'
                || '<tr style="background:#f1f5f9">'
                || '<th style="padding:4px 8px;border:1px solid #ddd">#</th>'
                || '<th style="padding:4px 8px;border:1px solid #ddd">Type</th>'
                || '<th style="padding:4px 8px;border:1px solid #ddd">Description</th>'
                || '<th style="padding:4px 8px;border:1px solid #ddd">Bill No</th>'
                || '<th style="padding:4px 8px;border:1px solid #ddd">Bill Date</th>'
                || '<th style="padding:4px 8px;border:1px solid #ddd">Period</th>'
                || '<th style="padding:4px 8px;border:1px solid #ddd">Amount</th>'
                || '<th style="padding:4px 8px;border:1px solid #ddd">USD</th></tr>';

    FOR b IN (SELECT item_no, bill_no, bill_date, type, description,
                     from_date, to_date, currency, amount, exchange_rate,
                     amount_usd, attachment_filename
              FROM   expense_items
              WHERE  expense_id = p_expense_id
              ORDER  BY item_no)
    LOOP
      l_bill_text := l_bill_text
        || b.item_no || '. ' || NVL(b.type, '-')
        || ' -- ' || NVL(b.description, '-') || CHR(10)
        || '     bill no ' || NVL(b.bill_no, '-')
        || ',  dated ' || NVL(TO_CHAR(b.bill_date, 'DD-Mon-YYYY'), '-') || CHR(10)
        || '     ' || NVL(TO_CHAR(b.from_date, 'DD-Mon-YYYY'), '-')
        || ' to '  || NVL(TO_CHAR(b.to_date,   'DD-Mon-YYYY'), '-') || CHR(10)
        || '     ' || TO_CHAR(b.amount) || ' ' || b.currency
        || '  =  ' || NVL(TO_CHAR(b.amount_usd), '-') || ' USD'
        || CASE WHEN b.exchange_rate IS NOT NULL AND b.currency != 'USD'
                THEN '   (1 ' || b.currency || ' = ' || TO_CHAR(b.exchange_rate) || ' USD)'
           END || CHR(10)
        || '     receipt: ' || NVL(b.attachment_filename, 'NONE') || CHR(10) || CHR(10);

      l_bill_html := l_bill_html
        || '<tr>'
        || '<td style="padding:4px 8px;border:1px solid #ddd">' || b.item_no || '</td>'
        || '<td style="padding:4px 8px;border:1px solid #ddd">'
        || NVL(DBMS_XMLGEN.CONVERT(b.type), '-') || '</td>'
        || '<td style="padding:4px 8px;border:1px solid #ddd">'
        || NVL(DBMS_XMLGEN.CONVERT(b.description), '-') || '</td>'
        || '<td style="padding:4px 8px;border:1px solid #ddd">'
        || NVL(DBMS_XMLGEN.CONVERT(b.bill_no), '-') || '</td>'
        || '<td style="padding:4px 8px;border:1px solid #ddd;white-space:nowrap">'
        || NVL(TO_CHAR(b.bill_date, 'DD-Mon-YYYY'), '-') || '</td>'
        || '<td style="padding:4px 8px;border:1px solid #ddd;white-space:nowrap">'
        || NVL(TO_CHAR(b.from_date, 'DD-Mon-YYYY'), '-') || ' to '
        || NVL(TO_CHAR(b.to_date,   'DD-Mon-YYYY'), '-') || '</td>'
        || '<td style="padding:4px 8px;border:1px solid #ddd;text-align:right;'
        || 'white-space:nowrap">' || TO_CHAR(b.amount) || ' ' || b.currency || '</td>'
        || '<td style="padding:4px 8px;border:1px solid #ddd;text-align:right;'
        || 'white-space:nowrap">' || NVL(TO_CHAR(b.amount_usd), '-') || '</td>'
        || '</tr>';
    END LOOP;

    l_bill_html := l_bill_html
      || '<tr style="background:#f8fafc">'
      || '<td colspan="7" style="padding:4px 8px;border:1px solid #ddd;'
      || 'text-align:right"><b>Total</b></td>'
      || '<td style="padding:4px 8px;border:1px solid #ddd;text-align:right;'
      || 'white-space:nowrap"><b>' || NVL(TO_CHAR(l_amount_usd), '-')
      || ' USD</b></td></tr></table>';

    l_bill_text := l_bill_text
      || RPAD('-', 60, '-') || CHR(10)
      || RPAD('Total (USD):', 22) || NVL(TO_CHAR(l_amount_usd), '-') || CHR(10);

    -- Worth saying out loud. A reviewer who sees three amounts and a USD total
    -- that is not their sum should be told why, not left to suspect an error.
    IF l_ccy_count > 1 THEN
      l_bill_text := l_bill_text || CHR(10)
        || 'Bills are in ' || l_ccy_count || ' different currencies, so the'  || CHR(10)
        || 'total is given in USD only -- each bill was converted at the'     || CHR(10)
        || 'rate for its own From Date.' || CHR(10);
      l_bill_html := l_bill_html
        || '<p style="color:#64748b;font-size:12px">Bills are in '
        || l_ccy_count || ' different currencies, so the total is given in USD '
        || 'only. Each bill was converted at the rate for its own From Date.</p>';
    END IF;
  END bill_table;

  PROCEDURE log_it(p_status IN VARCHAR2, p_err IN VARCHAR2 DEFAULT NULL) IS
  BEGIN
    INSERT INTO expense_mail_log (expense_id, event, mail_to, mail_cc, subject, status, error_text)
    VALUES (p_expense_id, p_event, l_to, l_cc, l_subject, p_status, p_err);
  END;

  -- Drops NULLs, duplicates, and anyone already in TO. Without this, someone
  -- who is the project manager on their own claim receives the same mail twice.
  FUNCTION cc_list(p_a IN VARCHAR2, p_b IN VARCHAR2 DEFAULT NULL) RETURN VARCHAR2 IS
    l_out VARCHAR2(4000);
    PROCEDURE add(p_e IN VARCHAR2) IS
    BEGIN
      IF p_e IS NULL THEN RETURN; END IF;
      IF UPPER(p_e) = UPPER(NVL(l_to, '~')) THEN RETURN; END IF;
      IF INSTR(UPPER(NVL(l_out, '')), UPPER(p_e)) > 0 THEN RETURN; END IF;
      l_out := CASE WHEN l_out IS NULL THEN p_e ELSE l_out || ',' || p_e END;
    END;
  BEGIN
    add(p_a); add(p_b);
    RETURN l_out;
  END;

BEGIN
  ------------------------------------------------------------------------------
  -- Gather
  ------------------------------------------------------------------------------
  SELECT e.emp_id, e.manager_empid, NVL(e.finance_manager_empid, get_finance_manager_empid()),
         e.project_id, e.amount, e.currency, e.amount_usd, e.exchange_rate,
         e.claim_for, e.submitted_at
  INTO   l_emp_id, l_mgr_id, l_fin_id,
         l_project_id, l_amount, l_currency, l_amount_usd, l_exchange_rate,
         l_claim_for, l_submitted_at
  FROM   expenses e
  WHERE  e.id = p_expense_id;

  -- Caller's values win. Without this the three lines below read stale data
  -- on the submit path and the whole email is about the wrong situation.
  l_mgr_id       := NVL(p_manager_empid, l_mgr_id);
  l_fin_id       := NVL(p_finance_empid, l_fin_id);
  l_submitted_at := NVL(p_submitted_at,  l_submitted_at);

  SELECT COUNT(*), COUNT(DISTINCT currency)
  INTO   l_item_count, l_ccy_count
  FROM   expense_items
  WHERE  expense_id = p_expense_id;

  BEGIN
    SELECT project_name INTO l_project_name
    FROM   projectmaster WHERE project_id = l_project_id;
  EXCEPTION WHEN OTHERS THEN l_project_name := NULL;
  END;

  FOR r IN (SELECT empid,
                   first_name || ' ' || last_name AS full_name,
                   ecode,
                   company_email
            FROM   employeedetails
            WHERE  empid IN (l_emp_id, l_mgr_id, l_fin_id))
  LOOP
    -- TRIM because a name built from two padded CHAR columns is all spaces
    -- when both are empty, and an all-space label renders as a blank table
    -- cell rather than tripping the NVL fallback in add_row.
    IF r.empid = l_emp_id THEN
      l_emp_name  := NULLIF(TRIM(r.full_name), '');
      l_emp_email := r.company_email;
      l_emp_label := TRIM(NVL(l_emp_name, 'Employee #' || r.empid)
                     || CASE WHEN TRIM(r.ecode) IS NOT NULL
                             THEN '(' || TRIM(r.ecode) || ')' END);
    END IF;
    IF r.empid = l_mgr_id THEN
      l_mgr_name  := NULLIF(TRIM(r.full_name), '');
      l_mgr_email := r.company_email;
      l_mgr_label := TRIM(NVL(l_mgr_name, 'Employee #' || r.empid)
                     || CASE WHEN TRIM(r.ecode) IS NOT NULL
                             THEN '(' || TRIM(r.ecode) || ')' END);
    END IF;
    IF r.empid = l_fin_id THEN
      l_fin_name  := NULLIF(TRIM(r.full_name), '');
      l_fin_email := r.company_email;
      l_fin_label := TRIM(NVL(l_fin_name, 'Employee #' || r.empid)
                     || CASE WHEN TRIM(r.ecode) IS NOT NULL
                             THEN '(' || TRIM(r.ecode) || ')' END);
    END IF;
  END LOOP;

  -- If a lookup found nothing at all, say so rather than leaving the row
  -- blank. A blank cell reads as a template bug; "Employee #3725 (not found)"
  -- points at the actual problem, which is the EMPLOYEEDETAILS row.
  l_emp_label := NVL(l_emp_label, 'Employee #' || l_emp_id || ' (not found)');
  l_mgr_label := NVL(l_mgr_label, CASE WHEN l_mgr_id IS NULL THEN 'not assigned'
                                       ELSE 'Employee #' || l_mgr_id || ' (not found)' END);
  l_fin_label := NVL(l_fin_label, CASE WHEN l_fin_id IS NULL THEN 'not assigned'
                                       ELSE 'Employee #' || l_fin_id || ' (not found)' END);

  -- Actor. is_finance_manager decides the role rather than comparing against
  -- manager_empid, because the same person can be both on different claims.
  IF p_actor_empid IS NOT NULL THEN
    l_actor_role :=
      CASE
        WHEN p_actor_role = 'FINANCE_MANAGER' THEN 'FM'
        WHEN p_actor_role = 'PROJECT_MANAGER' THEN 'PM'
        -- No role supplied: fall back to the event, which is unambiguous for
        -- every case except a revise/reject, where the caller must supply it.
        WHEN p_event = 'FINANCE_ACCEPTED'     THEN 'FM'
        WHEN p_event = 'MANAGER_ACCEPTED'     THEN 'PM'
        ELSE 'PM'
      END;
    IF p_actor_empid = l_emp_id THEN
      l_actor_name := l_emp_name;
    ELSIF p_actor_empid = l_mgr_id THEN
      l_actor_name := l_mgr_name;
    ELSIF p_actor_empid = l_fin_id THEN
      l_actor_name := l_fin_name;
    ELSE
      BEGIN
        SELECT first_name || ' ' || last_name INTO l_actor_name
        FROM   employeedetails WHERE empid = p_actor_empid;
      EXCEPTION WHEN OTHERS THEN l_actor_name := 'Employee #' || p_actor_empid;
      END;
    END IF;
  END IF;

  -- Remarks: the most recent comment at each stage, from the audit trail --
  -- so an approval email can quote what the manager said earlier.
  BEGIN
    SELECT MAX(comments) KEEP (DENSE_RANK LAST ORDER BY acted_at)
    INTO   l_mgr_remarks
    FROM   expense_approvals
    WHERE  expense_id = p_expense_id AND role = 'PROJECT_MANAGER';
  EXCEPTION WHEN OTHERS THEN l_mgr_remarks := NULL;
  END;

  BEGIN
    SELECT MAX(comments) KEEP (DENSE_RANK LAST ORDER BY acted_at)
    INTO   l_fin_remarks
    FROM   expense_approvals
    WHERE  expense_id = p_expense_id AND role = 'FINANCE_MANAGER';
  EXCEPTION WHEN OTHERS THEN l_fin_remarks := NULL;
  END;

  -- p_comment is the action just performed; it may not be committed to
  -- EXPENSE_APPROVALS yet from this autonomous transaction's point of view.
  IF p_comment IS NOT NULL THEN
    IF l_actor_role = 'FM' THEN l_fin_remarks := p_comment;
    ELSE                        l_mgr_remarks := p_comment;
    END IF;
  END IF;

  ------------------------------------------------------------------------------
  -- Recipients, greeting, subject
  ------------------------------------------------------------------------------
  IF p_event = 'SUBMITTED' THEN
    IF l_mgr_email IS NOT NULL THEN
      l_to        := l_mgr_email;
      l_cc        := cc_list(l_emp_email);
      l_greeting  := 'Dear ' || NVL(l_mgr_name, 'Project Manager');
      l_subject   := 'Expense #' || p_expense_id || ' awaiting your approval';
    ELSE
      -- No address to send to. TWO VERY DIFFERENT CAUSES, and conflating them
      -- produced a wrong and alarming message: a claim WITH a manager who has
      -- no email was reported as "no project manager assigned, cannot be
      -- approved" -- when in fact it can be approved perfectly well in the
      -- app, the manager just was not emailed.
      --
      --   manager_empid IS NULL  -> genuinely unassigned. Nobody can approve
      --                             it at the first stage. The claim is stuck.
      --   manager_empid set, but
      --   no COMPANY_EMAIL       -> approval works normally; only the
      --                             notification is lost.
      l_to        := l_emp_email;
      l_cc        := NULL;
      l_greeting  := 'Dear ' || NVL(l_emp_name, 'Colleague');
      IF l_mgr_id IS NULL THEN
        l_no_manager := TRUE;
        l_subject := 'Expense #' || p_expense_id
                     || ' submitted -- no project manager assigned';
      ELSE
        l_mgr_no_email := TRUE;
        l_subject := 'Expense #' || p_expense_id || ' submitted';
      END IF;
    END IF;
    l_actor_label := NVL(l_emp_name, 'the submitter');

  ELSIF p_event = 'MANAGER_ACCEPTED' THEN
    l_to        := l_fin_email;
    l_cc        := cc_list(l_mgr_email, l_emp_email);
    l_greeting  := 'Dear ' || NVL(l_fin_name, 'Finance Manager');
    l_actor_label := NVL(l_actor_name, l_mgr_name) || ' (PM)';
    l_subject   := 'Expense #' || p_expense_id || ' awaiting Finance approval';

  ELSIF p_event = 'FINANCE_ACCEPTED' THEN
    l_to        := l_emp_email;
    l_cc        := cc_list(l_mgr_email);
    l_greeting  := 'Dear ' || NVL(l_emp_name, 'Colleague');
    l_actor_label := NVL(l_actor_name, l_fin_name) || ' (FM)';
    l_subject   := 'Expense #' || p_expense_id || ' approved';

  ELSIF p_event IN ('REVISED', 'REJECTED') THEN
    l_to        := l_emp_email;
    l_cc        := cc_list(l_mgr_email);
    l_greeting  := 'Dear ' || NVL(l_emp_name, 'Colleague');
    l_actor_label := NVL(l_actor_name, 'a reviewer') || ' (' || NVL(l_actor_role, 'PM') || ')';
    l_subject   := 'Expense #' || p_expense_id ||
                   CASE WHEN p_event = 'REVISED' THEN ' sent back for revision'
                        ELSE ' rejected' END;
  ELSE
    l_subject := 'Unknown event ' || p_event;
    log_it('SKIPPED', 'Unrecognised event');
    COMMIT; RETURN;
  END IF;

  IF l_to IS NULL THEN
    log_it('SKIPPED', 'No TO address -- the relevant employee has no COMPANY_EMAIL');
    COMMIT; RETURN;
  END IF;

  ------------------------------------------------------------------------------
  -- Claim table
  ------------------------------------------------------------------------------
  l_body := l_greeting || CHR(10) || CHR(10)
         || 'This e-mail generated based on action performed by '
         || l_actor_label || '.' || CHR(10) || CHR(10)
         || 'Expense Claim' || CHR(10)
         || RPAD('-', 60, '-') || CHR(10);
  l_rows := NULL;

  add_row('Project Name:', l_project_name);

  IF p_event = 'SUBMITTED' THEN
    add_row('Claim Date:', TO_CHAR(NVL(CAST(l_submitted_at AS DATE), SYSDATE), 'DD-Mon-YYYY'));
    add_row('Claim For:', l_claim_for);
    add_row('Claim Total (USD):', total_usd_row);
  ELSE
    add_row('Employee(Ecode):', l_emp_label);
    add_row('Manager (Ecode):', l_mgr_label);
    add_row('Fin.Mgr(Ecode):', l_fin_label);
    add_row('Claim For:', l_claim_for);
    add_row('Claim Total (USD):', total_usd_row);

    IF p_event = 'FINANCE_ACCEPTED' THEN
      add_row('Manager Remarks:', l_mgr_remarks);
      add_row('Fin.Manager Remarks:', l_fin_remarks);
      add_row('Approved Amount:', total_usd_row);
    ELSIF p_event = 'MANAGER_ACCEPTED' THEN
      add_row('Manager Remarks:', l_mgr_remarks);
    ELSE
      -- REVISED / REJECTED: label the remark with whoever actually acted.
      add_row(CASE WHEN l_actor_role = 'FM' THEN 'Fin.Manager Remarks:'
                   ELSE 'Manager Remarks:' END,
              NVL(p_comment, CASE WHEN l_actor_role = 'FM' THEN l_fin_remarks
                                  ELSE l_mgr_remarks END));
    END IF;
  END IF;

  bill_table;
  l_body := l_body || l_bill_text;

  IF l_no_manager THEN
    l_body := l_body || CHR(10)
      || 'NOTE: this claim has no project manager assigned, so it cannot be'  || CHR(10)
      || 'approved at the first stage. Ask for a project manager to be set on' || CHR(10)
      || 'the project, then resubmit.' || CHR(10);
    l_rows := l_rows
      || '<tr><td colspan="2" style="padding:8px 10px;border:1px solid #f59e0b;'
      || 'background:#fef3c7;color:#92400e"><b>No project manager is assigned '
      || 'to this project</b>, so this claim cannot be approved at the first '
      || 'stage. Ask for one to be set, then resubmit.</td></tr>';

  ELSIF l_mgr_no_email THEN
    -- Deliberately reassuring rather than alarming: the workflow is fine.
    l_body := l_body || CHR(10)
      || 'NOTE: your project manager (' || l_mgr_label || ') has no email'    || CHR(10)
      || 'address on file, so they were not notified automatically. They can'  || CHR(10)
      || 'still approve this claim in the app -- you may want to tell them.'   || CHR(10);
    l_rows := l_rows
      || '<tr><td colspan="2" style="padding:8px 10px;border:1px solid #93c5fd;'
      || 'background:#eff6ff;color:#1e40af">Your project manager <b>'
      || DBMS_XMLGEN.CONVERT(l_mgr_label) || '</b> has no email address on '
      || 'file, so they were not notified. They can still approve this claim '
      || 'in the app.</td></tr>';
  END IF;

  l_body := l_body || CHR(10)
         || 'Open the Expenses app to view or act on this claim.' || CHR(10);

  l_html := '<div style="font-family:Segoe UI,Arial,sans-serif;font-size:14px;color:#0f172a">'
         || '<p>' || DBMS_XMLGEN.CONVERT(l_greeting) || '</p>'
         || '<p>This e-mail generated based on action performed by <b>'
         || DBMS_XMLGEN.CONVERT(l_actor_label) || '</b>.</p>'
         || '<p style="font-weight:700;margin-bottom:6px">Expense Claim</p>'
         || '<table style="border-collapse:collapse;border:1px solid #ddd">'
         || l_rows
         || '</table>'
         || l_bill_html
         || '<p style="color:#64748b;font-size:12px">Open the Expenses app to '
         || 'view or act on this claim.</p></div>';

  ------------------------------------------------------------------------------
  -- Send
  ------------------------------------------------------------------------------
  l_from      := NVL(secret('MAIL_FROM'), 'noreply@trinamix.com');
  l_workspace := secret('MAIL_WORKSPACE');

  BEGIN
    IF l_workspace IS NOT NULL THEN
      APEX_UTIL.SET_WORKSPACE(p_workspace => l_workspace);
    END IF;

    APEX_MAIL.SEND(
      p_to        => l_to,
      p_cc        => l_cc,
      p_from      => l_from,
      p_subj      => l_subject,
      p_body      => l_body,
      p_body_html => l_html
    );

    log_it('QUEUED');
    APEX_MAIL.PUSH_QUEUE;      -- SEND only queues; this hands it to the server

    UPDATE expense_mail_log SET status = 'PUSHED'
    WHERE  id = (SELECT MAX(id) FROM expense_mail_log
                 WHERE expense_id = p_expense_id AND event = p_event);
    COMMIT;

  EXCEPTION
    WHEN OTHERS THEN
      log_it('FAILED', SUBSTR(DBMS_UTILITY.FORMAT_ERROR_STACK, 1, 4000));
      COMMIT;
  END;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    l_subject := 'Expense ' || p_expense_id || ' not found';
    log_it('SKIPPED', 'No such expense');
    COMMIT;
  WHEN OTHERS THEN
    log_it('FAILED', SUBSTR(DBMS_UTILITY.FORMAT_ERROR_STACK, 1, 4000));
    COMMIT;
END send_expense_mail;
/


--------------------------------------------------------------------------------
-- 2. Recompile everything that went stale.
--
-- process_expense_action needs no source change -- it was only ever INVALID
-- because it calls send_expense_mail. recalc_claim_totals and the two triggers
-- on EXPENSES were invalidated by script 64's ALTER TABLE, which is normal and
-- clears on recompile; they are listed here so the run ends with nothing
-- INVALID rather than leaving ORDS to trip over one of them later.
--
-- ONLY the app's own objects. HRMS is a shared schema with roughly 190
-- pre-existing INVALID objects belonging to other systems. DBMS_UTILITY.
-- COMPILE_SCHEMA would touch all of them and is not ours to run.
--------------------------------------------------------------------------------
ALTER PROCEDURE process_expense_action COMPILE;
ALTER PROCEDURE recalc_claim_totals    COMPILE;


--------------------------------------------------------------------------------
-- 3. Verify. Zero rows from (a) and (b) is the pass condition.
--------------------------------------------------------------------------------

-- a) No app object may be INVALID. Named explicitly so the other systems'
--    broken objects do not drown the signal.
SELECT object_name, object_type, status
FROM   user_objects
WHERE  object_name IN ('SEND_EXPENSE_MAIL','PROCESS_EXPENSE_ACTION',
                       'RECALC_CLAIM_TOTALS','SEND_PUSH_NOTIFICATION',
                       'TEST_PUSH_NOTIFICATION','GET_REVIEWER_ROLE',
                       'IS_FINANCE_MANAGER','GET_FINANCE_MANAGER_EMPID',
                       'GET_PROJECT_MANAGER_EMPID','GET_EXCHANGE_RATE',
                       'CONVERT_TO_USD','IS_VALID_SESSION_TOKEN',
                       'CAN_VIEW_CLAIM','CAN_EDIT_CLAIM','PRICE_EXPENSE_ITEM',
                       'JSON_ESCAPE_STR','TRG_EXPENSES_AUDIT',
                       'TRG_COPY_PM_TO_EXPENSE')
AND    status != 'VALID'
ORDER  BY object_name;

-- b) And nothing may be left in user_errors for them.
SELECT name, type, line, position, text
FROM   user_errors
WHERE  name IN ('SEND_EXPENSE_MAIL','PROCESS_EXPENSE_ACTION','RECALC_CLAIM_TOTALS',
                'TRG_EXPENSES_AUDIT','TRG_COPY_PM_TO_EXPENSE')
ORDER  BY name, line, position;

-- c) The body must no longer mention the dropped columns, and must read the
--    items table. Expect: 0, 0, 1, and reads_items >= 2.
SELECT (SELECT COUNT(*) FROM user_source
        WHERE name = 'SEND_EXPENSE_MAIL' AND INSTR(LOWER(text), 'e.bill_no') > 0) AS ref_bill_no,
       (SELECT COUNT(*) FROM user_source
        WHERE name = 'SEND_EXPENSE_MAIL' AND INSTR(LOWER(text), 'e.type') > 0)    AS ref_type,
       (SELECT COUNT(*) FROM user_source
        WHERE name = 'SEND_EXPENSE_MAIL' AND INSTR(LOWER(text), 'e.claim_for') > 0) AS ref_claim_for,
       (SELECT COUNT(*) FROM user_source
        WHERE name = 'SEND_EXPENSE_MAIL'
        AND   INSTR(LOWER(text), 'expense_items') > 0)                            AS reads_items
FROM   dual;

-- d) The two triggers on EXPENSES. NOT part of this project -- they were found
--    during this diagnosis and nobody has explained them yet. Read what they
--    do before assuming they are harmless: TRG_COPY_PM_TO_EXPENSE sounds like
--    it writes MANAGER_EMPID, which the submit handler also writes, and if both
--    do it the last one wins.
SELECT trigger_name, trigger_type, triggering_event, status
FROM   user_triggers
WHERE  table_name = 'EXPENSES'
ORDER  BY trigger_name;


--------------------------------------------------------------------------------
-- 4. Then prove it with a real email, not by reading the source.
--
-- On dev: submit a claim with TWO bills in DIFFERENT currencies. That is the
-- case the old body got wrong in every possible way, so it is the only case
-- worth testing.
--
--   SELECT created_at, event, status, mail_to, mail_cc, subject, error_text
--   FROM   expense_mail_log ORDER BY id DESC FETCH FIRST 10 ROWS ONLY;
--
--   PUSHED  -- it left the database. Open the mail and check the bill table
--             lists BOTH bills, each in its own currency, with a USD total.
--   QUEUED  -- dev has no SMTP_HOST_ADDRESS. The body is still correct; you
--             just cannot see it. EMAIL_DEPLOY.sql 4 reports this.
--   FAILED  -- error_text carries the full stack.
--
--
-- ON PROD, run this BEFORE the next release, and note two things:
--
--   1. It fixes emails that are currently going out incomplete. It is not
--      optional cleanup.
--   2. Prod still has the legacy columns, because 64 3 was skipped there.
--      This script does not need them gone and does not touch them. When you
--      do finally drop them -- 67_multibill_stage5_cleanup.sql -- send_expense_
--      mail will already be ready, which is the whole point of doing this now.
--------------------------------------------------------------------------------
